# Generated by Django 3.2.8 on 2021-10-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('contract_address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('max_supply', models.IntegerField()),
                ('ipfs_hash', models.CharField(blank=True, max_length=46, unique=True)),
                ('api_url', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contract_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='TraitValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('rarity', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('trait_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.traittype')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('image_url', models.URLField()),
                ('rank', models.IntegerField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('contract_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('traits', models.ManyToManyField(to='project.TraitValue')),
            ],
        ),
        migrations.AddConstraint(
            model_name='traitvalue',
            constraint=models.UniqueConstraint(fields=('trait_type', 'name'), name='unique_trait_value'),
        ),
        migrations.AddConstraint(
            model_name='traittype',
            constraint=models.UniqueConstraint(fields=('contract_address', 'name'), name='unique_trait_type'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('contract_address', 'number'), name='unique_token'),
        ),
    ]
