# Generated by Django 3.2.8 on 2021-10-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='contract_address',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='traittype',
            old_name='contract_address',
            new_name='project',
        ),
    ]
