# Generated by Django 3.2.8 on 2021-10-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211012_0314'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='token',
            name='unique_token',
        ),
        migrations.RemoveConstraint(
            model_name='traittype',
            name='unique_trait_type',
        ),
        migrations.AlterField(
            model_name='token',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='traitvalue',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traitvalue',
            name='rarity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='traitvalue',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='unique_token'),
        ),
        migrations.AddConstraint(
            model_name='traittype',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_trait_type'),
        ),
    ]
