# Generated by Django 3.2.8 on 2021-10-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='token_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.tokentype'),
        ),
        migrations.AddConstraint(
            model_name='tokentype',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_token_type'),
        ),
    ]
