# Generated by Django 3.2.8 on 2021-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20211012_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitvalue',
            name='rarity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True),
        ),
    ]
