# Generated by Django 3.2.8 on 2021-10-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_traitvalue_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitvalue',
            name='rarity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
