# Generated by Django 3.2.8 on 2021-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20211013_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
