# Generated by Django 3.2.8 on 2021-10-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20211012_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='traittype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='traitvalue',
            options={'ordering': ['rarity']},
        ),
        migrations.AddField(
            model_name='token',
            name='os_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
