# Generated by Django 3.2.8 on 2021-10-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_token_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='tools_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
